apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: master
    owner: abayer
    repo: jx-demo-qs
  name: abayer-jx-demo-qs-master-1
spec:
  Status: ""
  params: null
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: abayer-jx-demo-qs-master-1
  resources:
  - name: abayer-jx-demo-qs-master
    resourceRef:
      apiVersion: tekton.dev/v1alpha1
      name: abayer-jx-demo-qs-master
  serviceAccount: tekton-bot
  trigger:
    type: manual
status:
  conditions: null
