trigger:
  trustedOrg: roadrunner-corp
schedulerAgent:
  agent: prow
policy:
  protectTested: true
merger:
  policy:
    fromBranchProtection: true
    skipUnknownContexts: false
postsubmits:
  items:
  - name: release
    context: ""
    branches:
      items:
      - master
    agent: tekton
presubmits:
  items:
  - name: integration
    agent: tekton
    alwaysRun: true
    context: integration
    rerunCommand: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
    query:
      labels:
        items:
          - approved
      missingLabels:
        items:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
    policy:
      protect: true
      requiredStatusChecks:
        contexts:
          items:
          - integration
plugins:
  items:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - override
