coverage:
        status:
          project:
            default:
              # basic
              target: auto
          patch:
            default:
              target: 70%
      codecov:
        ci:
          - !DCO
          - !Hound
          - !lint
          - !tide
          - integration
          - bdd