adminUser:
  password: vault:some-custer/adminUser:password
  username: test
enableDocker: false
pipelineUser:
  token: vault:cjxd-mole/pipelineUser:token
  email: test@test.org
  username: test
prow:
  hmacToken: vault:some-cluster/prow:hmacToken
