trigger:
  trustedOrg: roadrunner-corp
approve:
  lgtmActsAsApprove: true
  ignoreReviewState: false
externalPlugins:
  items:
  - name: jx-app-cheese
    endpoint: http://jx-app-cheese
schedulerAgent:
  agent: prow
policy:
  enforceAdmins: true
  protect: true
  protectTested: false
  requiredStatusChecks:
    strict: true
    contexts:
      items:
        - test1
        - test2
  restrictions:
    users:
      items:
        - user1
        - user2
    teams:
      items:
        - team1
        - team2
  requiredPullRequestReviews:
    dismissStaleReviews: true
    requireCodeOwnerReviews: false
    requiredApprovingReviewCount: 5
    dismissalRestrictions:
      users:
        items:
          - user1
          - user2
      teams:
        items:
          - team1
          - team2
merger:
  policy:
    fromBranchProtection: true
    skipUnknownContexts: false
postsubmits:
  items:
  - name: release
    context: ""
    branches:
      items:
      - master
    agent: tekton
presubmits:
  items:
  - name: integration
    agent: tekton
    alwaysRun: true
    context: integration
    rerunCommand: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
    query:
      labels:
        items:
          - approved
      missingLabels:
        items:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
    policy:
      protect: true
      requiredStatusChecks:
        contexts:
          items:
          - integration
plugins:
  items:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - override
