agent:
  label: jenkins-maven
pipelines:
  release:
    setup:
      steps:
      - container: maven
        steps:
        - cmd: mvn deploy
        - groovy: "dir(\"foo\") { \n  sh \"echo hello\"\n}"